version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.7"
  apt_packages:
    - cmake

sphinx:
  configuration: docs/source/conf.py

submodules:
  include: all

python:
  install:
    - requirements: docs/requirements.txt
    - method: setuptools
      path: .